# name: Deploy to Server
name: Make sure can build and deploy to server

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  CONTAINER_NAME: portfolio
  CONTAINER_TAG: papatenko/portfolio:latest
  PLATFORM: linux/amd64
  PORT: 4000
  RESTART_POLICY: always

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and CI
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # If want to use on Arm64, then add linux/arm64 on platforms
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/amd64
      #     push: true
      #     tags: ${{ env.CONTAINER_TAG }}

  # deploy:
  #   name: Deploy Docker Image to Server
  #   runs-on: self-hosted
  #   needs: build
  #   steps:
  #     - name: Grab from Docker Hub
  #       run: docker image pull $CONTAINER_TAG

  #     - name: Stop and remove old container
  #       run: docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME

  #     - name: Run new container
  #       run: docker run --platform $PLATFORM -d -p $PORT:$PORT --name $CONTAINER_NAME --restart $RESTART_POLICY $CONTAINER_TAG
